### ISSUE TITLE
Uncaught Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 1.0.0) or downgrade your runtime to an older version (== 1.0.0-rc.4).

### ISSUE THREAD

**Issue by abobwhite** [fuseelements/ember-brunch-skeleton#2]
Upon updating to the newest version of the skeleton, I am getting this error every now and then. It does not appear to be happening consistently (approx. every 3-4 brunch builds using brunch watch). To clarify, this is the javascript error I am getting when trying to load the page. I do have the newest handlebars and have updated the initialize.js to handle the template compilation. Any thoughts? Refreshing the page over and over does not change the result, however, running another brunch build does.

**Comment by jonbuffington** [comment]
@abobwhite You need to update your ember-handlebars-brunch plugin. See https://github.com/fuseelements/ember-brunch-skeleton/blob/master/package.json#L25

After updated your `package.json` file, you need to:

```
npm uninstall ember-handlebars-brunch
npm install ember-handlebars-brunch
```

**Comment by abobwhite** [comment]
@jonbuffington Thanks for the prompt reply. I have completely wiped out ember-handlebars-brunch and re-installed it exactly as you instructed and am still seeing the issue.

**Comment by jonbuffington** [comment]
@abobwhite The error message indicates you may be using an older (<RC7) `ember-handlebars-brunch` plugin. You should try removing your project''s `node_modules` and `public` directory and re-installing using `npm install`.

I have not been able to recreate this issue using the latest skeleton. I have also applied the changes to other existing projects successfully.

**Comment by abobwhite** [comment]
@jonbuffington Since I last posted, I have not changed anything, however, I have not seen the issue. Something on my end must have changed. If I start seeing issues again, I will take your advice. Thanks for the help.
